version: "3.3"

networks:
  mongo:
    external: true
  mongos:
    external: true

volumes:
    data: {}
    cfg: {}

services:

  data1:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - data:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == server1]
      resources:
        limits:
          cpus: '6.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 512M

  data2:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - data:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == server-jj95enl]
      resources:
        limits:
          cpus: '6.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 512M

  data3:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - data:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == tp01-2066]
      resources:
        limits:
          cpus: '6.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 512M

  cfg1:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - cfg:/data/configdb
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == server1]
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M

  cfg2:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - cfg:/data/configdb
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == server-jj95enl]
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M

  cfg3:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - cfg:/data/configdb
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == tp01-2066]
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M

  mongos1:
    image: mongo:3.4
    networks:
      - mongo
      - mongos
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == server-jj95enl]
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M

  mongos2:
    image: mongo:3.4
    networks:
      - mongo
      - mongos
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == tp01-2066]
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M

  bootstrap:
    image: stefanprodan/mongo-bootstrap:latest
    networks:
      - mongo
    command:
      - '-dataSet=datars/data1:27017,data2:27017,data3:27017'
      - '-configSet=cfgrs/cfg1:27017,cfg2:27017,cfg3:27017'
      - '-mongos=mongos1:27017,mongos2:27017'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == server1]
      resources:
        limits:
          cpus: '6.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 512M
